### ISSUE TITLE
Some comments and suggestions

### ISSUE THREAD

**Issue by c-sanchez** [BlueMagicalWolf/NoxPlayerPortable#1]
Hi, thanks by make this script to have Nox Player Portable.
Please update the link to current version, 6.6.0.8.
https://res06.bignox.com/full/20200529/2e4d6ce48ba64989b7ea16db43e63538.exe?filename=nox_setup_v6.6.0.8_full_intl.exe

i think its better to use HTTP Downloader instead of WGet.
WGet and their dlls are 2.83mb~, and downloads with just one connection.
HTTP Downloader are 548kb~ and we can download in multiple parts, so we have better download speeds.
https://github.com/erickutcher/httpdownloader
You need just create a empty "portable" named file (without extension) to make httpdownloader portable.

this is what I changed in your script for my use:

**Tools\httpd\httpd --parts 8 --immediate --url https://res06.bignox.com/full/20200529/2e4d6ce48ba64989b7ea16db43e63538.exe?filename=nox_setup_v6.6.0.8_full_intl.exe --output-directory "%~dp0\"**

You have used 7Zip (2.81mb~ the folder) but instead you can use the **7za** command line tool, what is just a single exacuble (574kb~)
or even **unzip** command line tool (135kb~)?

**Comment by BlueMagicalWolf** [comment]
http downloader isnt possible since windows defender detects it as malware

**Comment by BlueMagicalWolf** [comment]
> 
> 
> http downloader isnt possible since windows defender detects it as malware

i fixed the problem with enigma virtual box

**Comment by BlueMagicalWolf** [comment]
maybe its possible to use the build-in curl from windows to download the file

testing right now

**Comment by BlueMagicalWolf** [comment]
thanks for the suggestions, i've updated the script and it now uses http downloader and the cmd version of 7zip.

**Comment by BlueMagicalWolf** [comment]
> > http downloader isnt possible since windows defender detects it as malware
> 
> i fixed the problem with enigma virtual box

trick doesnt work anymore, its detected as malware again

for the people who doesnt want to use httpdownloader: https://github.com/BlueMagicalWolf/NoxPlayerPortable-Curl
