### ISSUE TITLE
Avoiding Nox instance data disk auto growth

### ISSUE THREAD

**Issue by FreedomLabsIO** [BlueMagicalWolf/NoxPlayerPortable#3]
Hi!

I have a couple of nox instances running Android 7 and they start with ~1.7 GB of data.
After a week or more it's almost 5 GB data and I have done nothing on it. I don't write any data or do any heavy work on it, just simple tasks that write no data to the disk.

 Is it possible to avoid disk size auto increasing if I make Nox portable like this or any modifications to it?

**Comment by Tha14** [comment]
That's not how virtual machines work. The size of the virtual disk will have to expand according to the data written within it. If you are desperate to reduce the size of the image you can try to go in Nox settings->Clean & Backup->Clean Up. I've never used it but I assume this is the one that compacts the virtual disk.

Also, I don't believe it will help much unless you can wipe the empty space within the virtual disk with zeroes. Just make sure you have a backup first before using that option.

**Comment by FreedomLabsIO** [comment]
> That's not how virtual machines work. The size of the virtual disk will have to expand according to the data written within it. If you are desperate to reduce the size of the image you can try to go in Nox settings->Clean & Backup->Clean Up. I've never used it but I assume this is the one that compacts the virtual disk.
> 
> Also, I don't believe it will help much unless you can wipe the empty space within the virtual disk with zeroes. Just make sure you have a backup first before using that option.

But I'm not writing any data to it as I explained...

Cleaning doesn't help either, it only removes ~300 mb of a 5 GB instance that initially had 2 GB.
What I'm doing is compressing the /data folder to the host pc with a .tar file and restoring it to a brand new instance.
But that is not very practical.

**Comment by Tha14** [comment]
> But I'm not writing any data to it as I explained...

Nox comes with google play services and play store installed. Play store auto-updates itself and other services and you cannot stop it from doing so. Also, don't forget about crash dumps, logs etc. I assure you, you are writing data to the disk whether you like it or not.

The only thing you could do is whether it's possible to change the virtual image size to a fixed size but then you're probably going to run out of disk space if it's too small and at some point it will start causing crashes and other unwanted behavior.

**Comment by FreedomLabsIO** [comment]
> > But I'm not writing any data to it as I explained...
> 
> Nox comes with google play services and play store installed. Play store auto-updates itself and other services and you cannot stop it from doing so. Also, don't forget about crash dumps, logs etc. I assure you, you are writing data to the disk whether you like it or not.
> 
> The only thing you could do is whether it's possible to change the virtual image size to a fixed size but then you're probably going to run out of disk space if it's too small and at some point it will start causing crashes and other unwanted behavior.

Got it... do you think it's possible to run it in non persistent mode, something like a live boot OS. So everytime I restart it is discards all the changes when in this mode ?

I did that once in a raspberry pi, to avoid corruption on the SD card due to abrupt shutdowns. Whenever I wanted to persist a data I had to execute a specific command to "unlock" and then "lock it" again. Restarting discards all the changes and writes to disk that were made in "locked mode", as they were made only in RAM.

**Comment by Tha14** [comment]
I don't think nox directly supports persistence. I've only used the backup/copy functionality of nox. If you go in the Nox multi-instance manager you can create copies and backups from there. The other thing you'd do would probably be to edit batch script to replace the image files with the ones you want. It's not a great way to do it but that's the only way I can think of.

**Comment by FreedomLabsIO** [comment]
VirtualBox supports immutable disks with the use of snapshots. Problem is that Nox overwrites any changes to the .vbox file and the snapshot folders. Have to investigate more about this.

https://www.kicksecure.com/wiki/VM_Live_Mode/Immutable_Disk_Method_on_VirtualBox

**Comment by FreedomLabsIO** [comment]
@Tha14 A quick workaround I found is to run the emulator inside [Sandboxie](https://github.com/sandboxie-plus/Sandboxie). All new data is discarded after closing it. And if you want to persist some data, just run it normally.

**Comment by Tha14** [comment]
> @Tha14 A quick workaround I found is to run the emulator inside [Sandboxie](https://github.com/sandboxie-plus/Sandboxie). All new data is discarded after closing it. And if you want to persist some data, just run it normally.

Yeah, that should work, all you have to do is to change the settings for the sandbox you'll be running it in and it will auto-clean.
